# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/albrightlabs/appreadme/models/document/columns.yaml

# Model Class name
modelClass: Albrightlabs\AppReadMe\Models\Document

# List Title
title: Manage Documents

# Link URL for each record
recordUrl: albrightlabs/appreadme/documents/preview/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: title
    direction: asc

# Display checkboxes next to each record
showCheckboxes: false

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
