# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Document

# Model Form Field configuration
form: $/albrightlabs/appreadme/models/document/fields.yaml

# Model Class name
modelClass: Albrightlabs\AppReadMe\Models\Document

# Default redirect location
defaultRedirect: albrightlabs/appreadme/documents

# Create page
create:
    title: backend::lang.form.create_title
    redirect: albrightlabs/appreadme/documents/preview/:id
    redirectClose: albrightlabs/appreadme/documents

# Update page
update:
    title: backend::lang.form.update_title
    redirect: albrightlabs/appreadme/documents/preview/:id
    redirectClose: albrightlabs/appreadme/documents

# Preview page
preview:
    title: backend::lang.form.preview_title
